### ISSUE TITLE
Analysis board bug with browser history

### ISSUE THREAD

**Issue by nrobinaubertin** [hiveboardgame/hive#277]
Reproduction:

1. have a real game ongoing
2. change the URL to `/analysis`
3. go back in history to the real game
4. go back to analysis using history forward
5. The analysis board is now set to be the game played
6. play a move on the analysis board, it will move it in the real game

This was done on firefox v127.0.2 on Ubuntu noble numbat.

**Comment by PenguinWithATie** [comment]
Hi I am following the steps on the same version of firefox but on step 5, i see an empty board and step 6 doesnt reproduce either, could you provide video or a game id?

**Comment by nrobinaubertin** [comment]
I retried in another game (https://hivegame.com/game/igZ4Zs72sJ). Those were I could reproduce it are correspondence games.  
I could repro only when it is my turn.  

This time I did the following:
1. go to the analysis board
2. click on the red envelope to be sent to one of my game
3. go back in history to the analysis mode

**Comment by PenguinWithATie** [comment]
Thanks for helping me with reproducing
