### ISSUE TITLE
Flake-based Nix setup

### ISSUE THREAD

**Issue by LucianU** [hiveboardgame/hive#90]
Hello

As I was telling @IongIer, I want to add a flake-based setup to your project.

My suggestion is to start with one that only provides the build tools. That is,
it won't also handle the build process itself. I think it would be too disruptive
for starters. Later, it can also do that.

For the setup, I need a list of all the tools used (compiler, package manager, etc.)
along with their versions.

**Comment by klautcomputing** [comment]
Thank for your PR and thanks for teaching me things! :slightly_smiling_face:

**Comment by LucianU** [comment]
You're welcome!
